-- PostgreSQL: preserve taxonomy arcs as independent rows.

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'taxonomy_presentation'
          AND column_name = 'id'
    ) THEN
        ALTER TABLE taxonomy_presentation
            DROP CONSTRAINT IF EXISTS taxonomy_presentation_pkey;
        ALTER TABLE taxonomy_presentation
            ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
        ALTER TABLE taxonomy_presentation
            ADD CONSTRAINT taxonomy_presentation_pkey PRIMARY KEY (id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'taxonomy_calculation'
          AND column_name = 'id'
    ) THEN
        ALTER TABLE taxonomy_calculation
            DROP CONSTRAINT IF EXISTS taxonomy_calculation_pkey;
        ALTER TABLE taxonomy_calculation
            ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
        ALTER TABLE taxonomy_calculation
            ADD CONSTRAINT taxonomy_calculation_pkey PRIMARY KEY (id);
    END IF;
END $$;

SELECT setval(
    pg_get_serial_sequence('taxonomy_presentation', 'id'),
    COALESCE(MAX(id), 1),
    MAX(id) IS NOT NULL
)
FROM taxonomy_presentation;

SELECT setval(
    pg_get_serial_sequence('taxonomy_calculation', 'id'),
    COALESCE(MAX(id), 1),
    MAX(id) IS NOT NULL
)
FROM taxonomy_calculation;

INSERT INTO schema_migrations (version, description)
VALUES ('V2.0', 'Preserve taxonomy presentation and calculation arc rows by identity')
ON CONFLICT (version) DO UPDATE SET description = EXCLUDED.description;
